// AUTO-GENERATED by scripts/pwa/vite-plugin-pwa.ts — do not edit by hand.
// Regenerated on every "npm run build"; CACHE_NAME changes every time
// (static-delivery-investigation.md §6.2 rule 1 — a fixed cache name is the
// classic permanent-stale bug).
const CACHE_NAME = "nouf-shell-0.0.0-20260808192457-6dc61d";
const RUNTIME_CACHE_NAME = "nouf-runtime-media-0.0.0-20260808192457-6dc61d";
const RUNTIME_CACHE_MAX_ENTRIES = 200;
const PRECACHE_URLS = ["./manifest.webmanifest","./robots.txt","./icons/favicon.svg","./assets/cairo-arabic-hmgdcmfj.woff2","./assets/index-elog40l3.js","./assets/index-l4l5l2k1.css"];

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      await cache.addAll(PRECACHE_URLS);
      // Seed the navigation document itself, best-effort. Without this,
      // only a SECOND (already SW-controlled) navigation would ever end up
      // cached, via networkFirst()'s own cache.put side effect — the very
      // first-ever page load necessarily happens before any service worker
      // exists to intercept it, so "after ONE successful visit, offline
      // works" would otherwise be false on a literal first-ever visit.
      try {
        await cache.add('./');
      } catch (err) {
        // Best-effort: a failure here must never fail the whole install.
      }
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys
            .filter((key) => key !== CACHE_NAME && key !== RUNTIME_CACHE_NAME)
            .map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

async function cacheFirst(request) {
  const cached = await caches.match(request, { cacheName: CACHE_NAME });
  if (cached) return cached;
  return fetch(request);
}

async function networkFirst(request) {
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      const cache = await caches.open(CACHE_NAME);
      cache.put(request, response.clone());
    }
    return response;
  } catch (err) {
    const cached = await caches.match(request, { cacheName: CACHE_NAME });
    if (cached) return cached;
    throw err;
  }
}

// Opportunistic, capped runtime cache for a PUBLISHED pack's media
// (questions.json / m/**) — these never exist inside this build's own
// PRECACHE_URLS (they are produced by a separate export flow and uploaded
// alongside dist/'s contents, not emitted by "npm run build"). A question
// already shown once replays offline; an unseen one may not — this is
// stated as a real limit, never promised as full offline media coverage
// (static-delivery-investigation.md §5.3's own honesty rule).
async function runtimeCached(request) {
  const cache = await caches.open(RUNTIME_CACHE_NAME);
  const cached = await cache.match(request);
  try {
    const response = await fetch(request);
    if (response && response.ok) {
      await cache.put(request, response.clone());
      const keys = await cache.keys();
      if (keys.length > RUNTIME_CACHE_MAX_ENTRIES) {
        await cache.delete(keys[0]);
      }
    }
    return response;
  } catch (err) {
    if (cached) return cached;
    throw err;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // The navigation document itself: network-first, never precached with a
  // hashed name (it has none — index.html is never renamed by the build).
  if (request.mode === 'navigate' || url.pathname.endsWith('/index.html')) {
    event.respondWith(networkFirst(request));
    return;
  }

  // Each precacheUrl is "./some/path" — slicing off the leading "."
  // leaves "/some/path", which the request's absolute pathname (under
  // whatever sub-path base it is served from) ends with regardless of
  // that base — no regex needed.
  const isPrecached = PRECACHE_URLS.some((precacheUrl) => url.pathname.endsWith(precacheUrl.slice(1)));
  if (isPrecached) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (url.pathname.indexOf('/m/') !== -1 || url.pathname.endsWith('questions.json')) {
    event.respondWith(runtimeCached(request));
    return;
  }

  // Everything else: default browser network behaviour, no caching.
});
